### ISSUE TITLE
remove "path" request from output report in .config

### ISSUE THREAD

**Issue by Erythroxylum** [marekborowiec/spruceup#10]
Hello Marek,

I am very excited to use this program to clean up my target capture alignments. Thanks for this program! 

One simple issue, line 81 of the .config file requests the path and filename for the output report file. The prefix then gets attached before the path and an error is generated:
`FileNotFoundError: [Errno 2] No such file or directory: '0.95_lognorms-cutoff-/my/path/report.txt'`

So it seems you should remove the prompt for the path in this part of the .config file.

Best,

Dawson

**Comment by marekborowiec** [comment]
Thanks for pointing this out. I clarified in the example configuration file that output must be file names only.
