### ISSUE TITLE
Unusual NameError: name 'command' is not defined

### ISSUE THREAD

**Issue by louisfnastasi** [marekborowiec/spruceup#15]
Hello,

I've been trying to use spruceup on some gall wasp UCE data I'm working with, but I've been receiving the following error:

<img width="1440" alt="image" src="https://github.com/marekborowiec/spruceup/assets/128258466/7a08c4db-ed6c-413d-bea8-da9169bf94f2">

I haven't been able to find anything regarding the "command" or "translate" elements mentioned in the error. Is anyone aware of how to resolve this issue? The contents of my configuration file are:

`[input]
input_file_name:/storage/group/hmh19/default/UCEs_working/taxon-sets/all/swsc-nexus-files/fifty-percent/fifty-percent-final-matrix-clean-iqtree-SWSC.nexus
input_format:nexus
data_type:nt
distances_object_file:
guide_tree:

[analysis]
cores:8
distance_method:uncorrected
window_size:50
overlap:25
fraction:1
criterion:lognorm
cutoffs:0.95,0.97,0.99
manual_cutoffs:

[output]
output_file_aln:fifty-spruceup-trimmed.nexus
output_format:nexus
report:fifty-spruceup-report.txt
log:fifty-spruceup-log.log`

Thanks in advance,

Louis Nastasi

**Comment by marekborowiec** [comment]
This should be fixed in the newest release
