### ISSUE TITLE
Setting cutoffs for weibull_min not described correctly

### ISSUE THREAD

**Issue by michael-branstetter** [marekborowiec/spruceup#16]
**Describe the bug**
The current readme documentation says to use fractions less than one for setting the cutoffs for weibull_min. However, the template config file says to use quantile values. Also the cutoffs for mean are whole integers, not fractions, yet the config file has a commented out cutoffs parameter that lists fractions. It seems to me that fractions should no longer be listed since they do not work for weibull_min or mean and lognorm is no longer a criterion. Can you clarify/fix this issue?

**Comment by marekborowiec** [comment]
I don't see an issue: The template cutoffs are set to integers because criterion is also set to "mean" by default, which is correct. I tried to further align README with config example so there's less ambiguity.
